#!/bin/bash

get_os() {
  uname -s
}
OS=`get_os`

if [[ $OS == "Linux" ]]; then
  OS=`lsb_release -i | awk -F ' ' '{print $3}'`
  VERSION=`lsb_release -r | awk -F ' ' '{print $2}'`
fi

INTERFACE=$1

export DOCKER_IP=127.0.0.1

if [[ $(docker network ls --filter="name=valet" -q) == "" ]]; then
  docker network create valet
fi

if [[ $OS == "Ubuntu" ]]; then
  sudo sed -i 's/dns=dnsmasq/#dnsmasq/' /etc/NetworkManager/NetworkManager.conf
  sudo pkill dnsmasq
  if [[ "$(grep $DOCKER_IP /etc/resolvconf/resolv.conf.d/head)" == "" ]]; then
    cat << VALET_EOF | sudo tee -a /etc/resolvconf/resolv.conf.d/head
nameserver $DOCKER_IP
VALET_EOF
    if [[ $VERSION == "16.04" ]]; then
      sudo systemctl restart NetworkManager.service
    fi
  fi
else
  if [[ ! -a /etc/resolver/dev || "$(grep $DOCKER_IP /etc/resolver/dev)" == "" ]]; then
    sudo mkdir -p /etc/resolver
    cat << RESOLVER_EOF | sudo tee /etc/resolver/dev
nameserver $DOCKER_IP
RESOLVER_EOF
  fi
fi

docker-compose up -d
